### ISSUE TITLE
Dev Server

### ISSUE THREAD

**Issue by dhilt** [BitDen/ui-scroll#4]
Это npm start. Он должен запускать npm run dev-build. В конфиге Webpack в дев-режиме нужно добавить dev server на 5005 порту. См https://webpack.js.org/configuration/dev-server/#src/components/Sidebar/Sidebar.jsx. Нужно научить его отдавать ./demo/index.html, для этого см. https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback. В демках все ссылки ведут на ./dist, и старый Грант перекидывал через middleware запросы с ./dist на ./temp. Мы должны научить вебпак выдавать дистрибутив из памяти в ответ на ./dist запросы. Нам не нужно выдавать содержимое ./dist, как в примере в документации, нам нужно выдавать бандлы из памяти. Кстати, возможно через contentBase будет проще выдавать статику (включая index.html), чем через historyapifallback... 

Этот вопрос освещен широко и возможно решение тривиально, см. например https://stackoverflow.com/questions/36306141/webpack-dev-server-serving-in-different-folder-than-webpack-output...

**Comment by dyuv-dev** [comment]
@dhilt Пока что не удалось сделать вылавливание .js-файлов из памяти, но уже есть вопрос насчет правильности изначальной команды в package.json. Команда `webpack-dev-server --config webpack/config.js` это же и есть по сути `npm run dev-build`? Вроде поведение то же самое, исключая момент что первая команда не создает кучу *Spec.js-файлов в корневой папке.
Коммит - https://github.com/BitDen/ui-scroll/commit/1a60fafd5b8255e014b5392654c6d296cebdc47f.

**Comment by dhilt** [comment]
@BitDen Дев-сервер по умолчанию должен обслуживать указанный порт бандлами из памяти. Для этого он  и создавался.

> webpack-dev-server serves all assets from in-memory, but if you use the contentBase option (which defaults to your current working directory), it will serve those files from disk. The in-memory files are preferred above the contentBase files though.

Пробуй модифицировать процедуру, у меня может быть неточное или даже неправильное видение до того, как я сам не займусь этим.

И давай пока уберем засор из спек в корне.

**Comment by dyuv-dev** [comment]
@dhilt Cделал рабочую версию devServer'а - https://github.com/BitDen/ui-scroll/commit/2c0b79a4c14ef7d7e3f32db54cf13a16f2b53c87.
Работающую только для одного компонента. С моим подходом в применении historyapifallback придется очень так хорошо извернуться в коде, что не получилось много строк. Только в этом коммите он помимо бандлов из памяти выдает еще html-странички (по задумке должен все html-странички выдавать, но так как это эдакая демо-версия, показывает только одну).

И видимо стоит как-то ему запретить отслеживание изменений и пересборку бандлов (ибо этим должен быть занят `npm run dev-build`)?

**Comment by dyuv-dev** [comment]
@dhilt Ах да, там же можно хитро функцию вписать и код будет славно выглядеть, сейчас попробую...

**Comment by dyuv-dev** [comment]
@dhilt Готово - https://github.com/BitDen/ui-scroll/commit/96b4e1d1a8d6c2e00b3b0c9a2b5757d80848ab91.

**Comment by dyuv-dev** [comment]
@dhilt И еще отыскал два недостающих jshint-ключа, чтобы предупреждения в консоли убрать - https://github.com/BitDen/ui-scroll/commit/9ada21cb5e3dc5d1e484c622efdbc9b72c9e48b9. Взгляните пожалуйста, все ли они к месту и нужны ли.

**Comment by dhilt** [comment]
@BitDen Конечно, dev-server должен пересобирать дистрибутив по изменениям в ./src. В этом и заключается смысл локальной разработки. Трудности будут, когда мы будем соединять тесты и dev-server. По изменению в ./src должны будут пересобираться исходники в памяти, выдаваемые по запросу на наш порт, а также запускаться тесты. Это конечная цель npm start. То есть это должно стать похоже на 

```
"start": "npm run dev-server & npm run dev-tests"
```

где вместо &, конечно, concurrently. Сам сервер я еще не смотрел.

**Comment by dhilt** [comment]
@BitDen В общем сейчас твой dev-server не выдает дистрибутива из памяти. Изменение кода приводит к пересборке в памяти, но сами демки по-прежнему тянут сорсцы из ./dist так, как это прописано в их html script-тегах. Заставь dev-server перехватывать запросы к ./dist. В старом сборщике за это отвечал Grunt middleware: https://github.com/angular-ui/ui-scroll/blob/master/Gruntfile.js#L18

**Comment by dyuv-dev** [comment]
@dhilt Вроде бы все перепробовал, что возможно сделать с devServer в конфиге и как-то ничего не выходит пока.

**Comment by dyuv-dev** [comment]
@dhilt Есть идея сделать отдельный сервер по следующим стопам - https://webpack.js.org/guides/development/#using-webpack-dev-middleware.
И далее в нашем конфиге через proxy доставать нужные файлы из памяти.
Но чувствую это может получиться очень избыточно по количеству коду, если конечно же вообще получится)

**Comment by dyuv-dev** [comment]
И нет, с этим тоже ничего не вышло.

**Comment by dhilt** [comment]
@BitDen Я сделал фикс. Ты был почти близок, манипуляции с путями и настройками отняли у меня 45 минут времени, это было не самое тривиальное место. Можно переходить к интеграции dev-server и dev-test. С учетом того, что оба процесса работают через вебпак, это может быть очень непросто.

**Comment by dyuv-dev** [comment]
@dhilt Ох, коварный ключик "hot".

Интеграция dev-server и dev-test - это то, чего мы в идеале хотим от следующей команды?
```
"start": "concurrently \"npm run dev-server\" \"npm run dev-test\""
```

**Comment by dyuv-dev** [comment]
@dhilt Если да, то все вроде бы здорово, изменения в ./src отслеживаются. Только шибко много всего выводится в консоль. Ну и две сборки идет.
Коммит - https://github.com/BitDen/ui-scroll/commit/195d10970a83e8dd96b34e0f873c87ea7a7f3851.

**Comment by dhilt** [comment]
@BitDen Я уменьшил количество логов. Отказался от concurrently в пользу npm-run-all. Надо к полученному результату заставить также Вебпак под Кармой не выводить подробности. И поступить нужно таким образом.

devServer должен конфигурироваться не всегда. Разводки по prod и dev не достаточно. Особый случай должен представлять скрипт dev-test. В нем, хоть и настраивается dev-окружение, но devServer инициализироваться не должен. Добавь в webpack флаг isTest, который бы уточнял переменную окружения ENV. И в dev-режиме инициализируй devServer, только если isTest == false.

И еще давай вернем конфиг на место ./webpack.config.js

**Comment by dyuv-dev** [comment]
@dhilt Новую переменную окружения добавил - https://github.com/BitDen/ui-scroll/commit/ecb8e2e56df9af8ab0d2cd3ee44e62d7d207095c.
Конфиг перенес - https://github.com/BitDen/ui-scroll/commit/1da0dca300d9e7ab701489678bbaf182e8f8a3d6.

Из проблем только то, что при dev-build файлы ui-scroll.js и ui-scroll-grid.js компилируются в корневую папку, уже не помню было ли это до моего коммита или нет.

**Comment by dhilt** [comment]
Не было на предпоследней итерации. Это легко проверить, открывший локально
по дереву комитов. Весь дев должен осуществляться в памяти без каких либо
следов, особенно в корне.
18 Ноя 2017 г. 0:19 пользователь "Denis Iuvzhenko" <notifications@github.com>
написал:
>
> @dhilt Новую переменную окружения добавил - ecb8e2e.
> Конфиг перенес - 1da0dca.
>
> Из пробблем только то, что при dev-build файлы ui-scroll.js и
ui-scroll-grid.js компилируются в корневую папку, уже не помню было ли это
до моего коммита или нет.

**Comment by dyuv-dev** [comment]
@dhilt Хм, совсем не понимаю как возможно с помощью `webpack` держать файлы в памяти, мне казалось для этого случая только `webpack-dev-server` годится.

**Comment by dyuv-dev** [comment]
@dhilt Решил проверить было ли это раньше, откатился до следующего коммита - https://github.com/BitDen/ui-scroll/commit/1909652630d6c00b2b328e36c9ad01c06ae74f4b. И все-таки там была эта проблема, если это конечно вообще проблема, так как вижу `npm run dev-build` нигде собственно и не используется.

Может произошла путаница и вместо следующих двух npm-скриптов
```
"dev-build": "webpack",
"dev-server": "webpack-dev-server",
```
у нас должен быть следующий один скрипт?
```
"dev-build": "webpack-dev-server"
```

**Comment by dhilt** [comment]
@BitDen Точно, ты прав, это я по утру спутал.

**Comment by dhilt** [comment]
@BitDen Я решил оставшиеся проблемы. Посмотри в частности https://stackoverflow.com/questions/47291494/how-to-jshint-two-different-folders-with-webpack. Если ты согласен с решением, just accept the answer. Также я перевел подмену /dist/ui-scroll*.js на in-memory bundles с historyApiFallback на proxy. И еще отдельные мелочи. Посмотри, пожалуйста, что все срослось как надо, перечисли недочеты и будем двигаться к закрытию этой темы. Последним этом будет подготовка PR, там будет, возможно, не очень быстро, но просто.

**Comment by dyuv-dev** [comment]
@dhilt Первое что смущает, что при старте `npm run dev-server` jshint показывает разное отношение к ошибкам в ./test и в ./src. Если что-то не так написано в ./test, то мы получаем в консоли просто предупреждение. Если же что-то не так в ./src, то это ошибка, не дающая webpack'у сделать сборку. Может стоит для двух папок сделать одинаковое отношение к появлению ошибок?
Ну и второе. При `npm run dev-test` делаем сборку файлов из ./test. Но это я так понимаю неизбежное зло?

**Comment by dyuv-dev** [comment]
@dhilt А для таинственного travis'а послужит команда `npm run build`, как я понимаю. Только вот в Gruntfile.js не было прогона по jshint, может это лишнее для travis? Это третий пункт, что я заметил. А так в остальном все шикарно, как по мне.

**Comment by dhilt** [comment]
@BitDen С Трависом будем экспериментировать на живом. Если prod build не пойдет, сделаем отдельную команду, отдельное окружение с нужным количеством всего. А сейчас поступим таким образом: https://github.com/BitDen/ui-scroll/issues/5.

**Comment by dhilt** [comment]
@BitDen С тестами мы не можем завалить сборку ui-scroll бандла, нам подвластен в этом случае только бандл test. И провал jshint на тестах не является блокирующим относительно основной сборки.
