### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by dhilt** [BitDen/ui-scroll#5]
~~Нужно сделать новый бранч от комита с которого мы начали развивать этот форк. Бранч "webpack". А именно от комита 5dd968ce50c63cd0d4790a6c25e317de631e34ce. Затем нужно влить в этот бранч изменения, сделанные в основном репозитории (с тех пор я успел еще один релиз сделать). Вот базовая инструкция для этого: https://help.github.com/articles/syncing-a-fork/. Только в п.4 switch нужно делать не в 'master', а в 'webpack'.~~

Я подумал 57 комитов погоду не испортят. Конечно, было бы неплохо вычистить историю, повторив наш подвиг в, скажем, 10 чистых комитов. Но давай просто выполним мерж текущего мастера оригинального репозиотрия в мастер форка. Даже не так. Я создал бранч 'webpack' в оригинальном репозитории. Так вот, мастер форка нужно синхронизовать с бранчем 'webpack' оригинального репозиотрия. Там могут быть и будут проблемы.

**Comment by dyuv-dev** [comment]
@dhilt А если бы я допустим скопировал где-то у себя папку ui-scroll, заново сделал форк от оригинального репозитория, далее вернул бы папку на место (за исключением .git внутри наверное), и сделал бы один коммит со всеми изменениями? Или же это совсем беспощадно в плане количества информации на один коммит?

**Comment by dyuv-dev** [comment]
@dhilt И, пока что не совсем понимаю как сделать мерж оригинального репозитория в мастер нашего форка.

**Comment by dyuv-dev** [comment]
@dhilt Возможно следующими тремя командами - https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/ можно было бы забрать с оригинального репозитория изменения из бранча master и далее сделать `git push upstream master`?

**Comment by dyuv-dev** [comment]
@dhilt Так, я в общем не дождался ответа и слил уже изменения в форк. Коммит - https://github.com/BitDen/ui-scroll/commit/73fedd1c233e8599d6db91842406c0f6ea4f346c.

Конфликтов было всего шесть:
1. test/misc/datasources.js - здесь были какие-то несовпадения, хотя вроде бы мы в форке не трогали этот файл вовсе. В общем я его полностью скопировал из изменившегося оригинального репозитория.
2. test/config/karma.conf.files.js - здесь добавились две новые строчки. Последнюю судя по всему стоило удалить (https://github.com/BitDen/ui-scroll/commit/73fedd1c233e8599d6db91842406c0f6ea4f346c#diff-0bc36d9997325408f9ba9d1aa267cc94R9), но я на всякий случай закомментировал, мало ли.
3. test/UserIndiciesSpec.js - этот файл был то ли удален, то ли переименован в оригинальном репозитории. В форке теперь его нет в общем, удалил.
4. (и 5, 6) В папке ./test файлы PaddingSpec.js, BasicTestsSpec.js, BasicSetupSpec.js - здесь попросту нужно было убрать самую первую строчку кода с комментариями, ничего серьезного. (! И следуя традиции надо убрать строчку комментария в новой спеке UserIndicesSpec.js)

В итоге, все npm-скрипты удачно проходят за исключением тех, кто включает в себя jshint. С этим есть проблемы. Ругается на необъявленную переменную Helper, на неиспользование use strict и еще что-то.

И вдобавок сделал rebuild проекта, в ./dist сейчас свежие файлы, так сказать.

**Comment by dyuv-dev** [comment]
@dhilt jshint ругается похоже только по четырем поводам. Helper, use strict, нестрогий синтаксис в четырех местах. То есть требует чтобы это
```
if (i > -3 && i < 1)
  result.push('item' + i);
```
было написано так:
```
if (i > -3 && i < 1) {
  result.push('item' + i);
}
```

И четвертым идет файл test/misc/helpers/js с переменной, которая по мнению jshint нигде не используется.

**Comment by dhilt** [comment]
@BitDen Я поправил datasources, но этот код был в предыдущем перед мержем комите: https://github.com/BitDen/ui-scroll/blob/9734117cd835f138b32f875516af3554be88445b/test/misc/datasources.js. Это ты неправильно конфликт разрешил. Остальное я тоже исправил. 

И открыл https://github.com/angular-ui/ui-scroll/pull/193.

**Comment by dhilt** [comment]
Пока не очень успешно: https://travis-ci.org/angular-ui/ui-scroll/builds/304361878?utm_source=github_status&utm_medium=notification. Травис обиделся на FF. Сейчас буду пытаться править.

**Comment by dyuv-dev** [comment]
@dhilt Йех, извиняюсь конечно за datasources.

Но сейчас похоже все уже в порядке?

**Comment by dhilt** [comment]
@BitDen Да. Теперь я приму PR, подправлю документацию, вольюсь в мастер и выпущу наконец 1.7.0! Этот репозиторий рекомендую не удалять, может пригодиться для демонстрации твоего участия в open source.

**Comment by dyuv-dev** [comment]
@dhilt Классно. Репозиторий конечно оставлю, правда вклад в open source получился совсем небольшой, но уже что-то.
